version: "3.7"

services:

  backend:
    image: di_full_ref_backend

    build:
      context: ./
      dockerfile: Dockerfile

    container_name: dc_full_ref_backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/usr/src/Documents/dev/full_ref_backend

    depends_on:
      - db

    # networks:
    #   - full_ref_net

    command: >
      bash -c "
        python manage.py runserver 0.0.0.0:8000"
  
  db:
    image: postgres:latest
    restart: always
    container_name: dc_full_ref_db
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - TZ=Asia/Seoul

    volumes:
      - ./postgres_data:/usr/src/Documents/dev/full_ref_backend/postgres_data

    # networks:
    #   - full_ref_net

networks:
  default:
    external:
      name: full_ref_net